### ISSUE TITLE
3.1.5 版本不兼容

### ISSUE THREAD

**Issue by WEREGV** [HowcanoeWang/siyuan-genshin-launcher#11]
作者大大可以支持兼容一下思源 3.1.5 吗

**Comment by HowcanoeWang** [comment]
自己也很久没用了，有什么兼容问题吗？

**Comment by driekey** [comment]
我这里倒是出现了, PDF文件打开失败的问题. 
在使用该插件时后台报错

```txt
plugin:siyuan-color-scheme:112 你好，配色插件！
plugin:siyuan-genshin-launcher:24 [Genshin Plugin][INFO] [waifu.ts][prepareWaifu] unzip paimon.zip
plugin:siyuan-genshin-launcher:24 [Genshin Plugin][INFO] 源神，启动！
plugin:kmind-plugin:31 res: {"newKmindAutoZenMode":true,"newKmindAutoSelectStructure":"logicalStructure","newKmindAutoSelectTheme":"classic7","newKmindAutoOutlineMode":false,"leftKeySelectionRightKeyDrag":false,"openKmindAutoZenMode":false,"openKmindAutoReadOnlyMode":false}
plugin:kmind-plugin:31 globalConfig: Object
app/:1 Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at l (plugin:kmind-plugin:602:3615)
plugin:siyuan-genshin-launcher:24 [Genshin Plugin][INFO] frontend: desktop; backend: windows
plugin:siyuan-genshin-launcher:24 [Genshin Plugin][INFO] [waifu.ts][hoverTransparent] deactivate waifu transparent, true
plugin:siyuan_rmv_btn:1 [Deprecation] Listener added for a 'DOMNodeInserted' mutation event. This event type is deprecated, and will be removed from this browser VERY soon. Usage of this event listener will cause performance issues today, and represents a large risk of imminent site breakage. Consider using MutationObserver instead. See https://chromestatus.com/feature/5083947249172480 for more information.
rmvMenuItems @ plugin:siyuan_rmv_btn:1
plugin:siyuan_rmv_btn:1 移除按钮插件: 上方的warning是因为您选择了高性能的监听方式,若不喜欢,请在设置页面选择另外两种方式,谢谢
theme.js?v=5.1.3:2392 ==============>附加CSS和特性JS_已经执行<==============
main.1f4fb9245cda9f31037d.js:3573 The Preferences may override manually set AppOptions; please use the "disablePreferences"-option to prevent that.
ws._checkDisablePreferences @ main.1f4fb9245cda9f31037d.js:3573
main.1f4fb9245cda9f31037d.js:3596 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'shadow')
    at get externalServices (main.1f4fb9245cda9f31037d.js:3596:43462)
    at LE.initialize (main.1f4fb9245cda9f31037d.js:3596:34744)
    at async LE.run (main.1f4fb9245cda9f31037d.js:3596:41627)
main.1f4fb9245cda9f31037d.js:3569 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: http://127.0.0.1:52202/stage/build/app/1d9e47ce7f6576ce7bae.woff2
main.1f4fb9245cda9f31037d.js:3596 Uncaught TypeError: Cannot read properties of null (reading 'currentPageNumber')
    at get page (main.1f4fb9245cda9f31037d.js:3596:44034)
    at Oi (main.1f4fb9245cda9f31037d.js:4656:13954)
    at Oi (main.1f4fb9245cda9f31037d.js:4656:14938)
    at main.1f4fb9245cda9f31037d.js:4656:14884
    at Array.forEach (<anonymous>)
    at Oi (main.1f4fb9245cda9f31037d.js:4656:14842)
    at main.1f4fb9245cda9f31037d.js:4656:14884
    at Array.forEach (<anonymous>)
    at Oi (main.1f4fb9245cda9f31037d.js:4656:14842)
    at main.1f4fb9245cda9f31037d.js:4656:14884
    at Array.forEach (<anonymous>)
    at Oi (main.1f4fb9245cda9f31037d.js:4656:14842)
    at main.1f4fb9245cda9f31037d.js:4656:14884
    at Array.forEach (<anonymous>)
    at Oi (main.1f4fb9245cda9f31037d.js:4656:14842)
    at un (main.1f4fb9245cda9f31037d.js:4656:7251)
    at main.1f4fb9245cda9f31037d.js:4656:7380
main.1f4fb9245cda9f31037d.js:3596 Uncaught TypeError: Cannot read properties of null (reading 'currentPageNumber')
    at get page (main.1f4fb9245cda9f31037d.js:3596:44034)
    at Oi (main.1f4fb9245cda9f31037d.js:4656:13954)
    at Oi (main.1f4fb9245cda9f31037d.js:4656:14938)
    at main.1f4fb9245cda9f31037d.js:4656:14884
    at Array.forEach (<anonymous>)
    at Oi (main.1f4fb9245cda9f31037d.js:4656:14842)
    at main.1f4fb9245cda9f31037d.js:4656:14884
    at Array.forEach (<anonymous>)
    at Oi (main.1f4fb9245cda9f31037d.js:4656:14842)
    at main.1f4fb9245cda9f31037d.js:4656:14884
    at Array.forEach (<anonymous>)
    at Oi (main.1f4fb9245cda9f31037d.js:4656:14842)
    at main.1f4fb9245cda9f31037d.js:4656:14884
    at Array.forEach (<anonymous>)
    at Oi (main.1f4fb9245cda9f31037d.js:4656:14842)
    at un (main.1f4fb9245cda9f31037d.js:4656:7251)
    at main.1f4fb9245cda9f31037d.js:4544:2535
get page @ main.1f4fb9245cda9f31037d.js:3596
Oi @ main.1f4fb9245cda9f31037d.js:4656
Oi @ main.1f4fb9245cda9f31037d.js:4656
（匿名） @ main.1f4fb9245cda9f31037d.js:4656
Oi @ main.1f4fb9245cda9f31037d.js:4656
（匿名） @ main.1f4fb9245cda9f31037d.js:4656
Oi @ main.1f4fb9245cda9f31037d.js:4656
（匿名） @ main.1f4fb9245cda9f31037d.js:4656
Oi @ main.1f4fb9245cda9f31037d.js:4656
（匿名） @ main.1f4fb9245cda9f31037d.js:4656
Oi @ main.1f4fb9245cda9f31037d.js:4656
un @ main.1f4fb9245cda9f31037d.js:4656
（匿名） @ main.1f4fb9245cda9f31037d.js:4544
setTimeout
on @ main.1f4fb9245cda9f31037d.js:4544
（匿名） @ main.1f4fb9245cda9f31037d.js:7222
main.1f4fb9245cda9f31037d.js:3596 Uncaught TypeError: Cannot read properties of null (reading 'currentPageNumber')
    at get page (main.1f4fb9245cda9f31037d.js:3596:44034)
    at Oi (main.1f4fb9245cda9f31037d.js:4656:13954)
    at Oi (main.1f4fb9245cda9f31037d.js:4656:14938)
    at main.1f4fb9245cda9f31037d.js:4656:14884
    at Array.forEach (<anonymous>)
    at Oi (main.1f4fb9245cda9f31037d.js:4656:14842)
    at main.1f4fb9245cda9f31037d.js:4656:14884
    at Array.forEach (<anonymous>)
    at Oi (main.1f4fb9245cda9f31037d.js:4656:14842)
    at main.1f4fb9245cda9f31037d.js:4656:14884
    at Array.forEach (<anonymous>)
    at Oi (main.1f4fb9245cda9f31037d.js:4656:14842)
    at main.1f4fb9245cda9f31037d.js:4656:14884
    at Array.forEach (<anonymous>)
    at Oi (main.1f4fb9245cda9f31037d.js:4656:14842)
    at un (main.1f4fb9245cda9f31037d.js:4656:7251)
    at main.1f4fb9245cda9f31037d.js:4544:2535
get page @ main.1f4fb9245cda9f31037d.js:3596
Oi @ main.1f4fb9245cda9f31037d.js:4656
Oi @ main.1f4fb9245cda9f31037d.js:4656
（匿名） @ main.1f4fb9245cda9f31037d.js:4656
Oi @ main.1f4fb9245cda9f31037d.js:4656
（匿名） @ main.1f4fb9245cda9f31037d.js:4656
Oi @ main.1f4fb9245cda9f31037d.js:4656
（匿名） @ main.1f4fb9245cda9f31037d.js:4656
Oi @ main.1f4fb9245cda9f31037d.js:4656
（匿名） @ main.1f4fb9245cda9f31037d.js:4656
Oi @ main.1f4fb9245cda9f31037d.js:4656
un @ main.1f4fb9245cda9f31037d.js:4656
（匿名） @ main.1f4fb9245cda9f31037d.js:4544
setTimeout
on @ main.1f4fb9245cda9f31037d.js:4544
（匿名） @ main.1f4fb9245cda9f31037d.js:7222
setTimeout
（匿名） @ main.1f4fb9245cda9f31037d.js:7222

```

**Comment by HowcanoeWang** [comment]
@driekey 可能是思源新版启动时增加了什么代码，我抽空排查一下
