### ISSUE TITLE
思源原神主题看板娘丢失

### ISSUE THREAD

**Issue by Garfield12138** [HowcanoeWang/siyuan-genshin-launcher#6]
派蒙看板娘无法显示
隐藏开关和悬浮半透明都打开了
![image](https://github.com/HowcanoeWang/siyuan-genshin-launcher/assets/138197235/0b17d815-8cc8-4527-a882-7391682a6461)
![image](https://github.com/HowcanoeWang/siyuan-genshin-launcher/assets/138197235/f00ad588-8817-485b-af9c-df713cab4a47)

**Comment by HowcanoeWang** [comment]
开发者模式打开，然后ctrl+shift+r刷新有什么报错没有？

**Comment by Garfield12138** [comment]
![image](https://github.com/HowcanoeWang/siyuan-genshin-launcher/assets/138197235/97f43943-62b0-4612-8021-6d6859f8803e)
就这一段显示有问题

**Comment by HowcanoeWang** [comment]
可是这是数学公式插件的报错呀，这个插件是siyuan-genshin-launcher，截图里没有任何相关的报错信息

**Comment by Garfield12138** [comment]
抱歉，看错了，但看板娘还是打不开，开发者模式那边没有显示问题

**Comment by HowcanoeWang** [comment]
看图标像是linux平台？用的是什么系统和桌面？

**Comment by HowcanoeWang** [comment]
升级到思源2.10.13后，发现可以复现这个问题，因为升级了electron的版本：https://github.com/siyuan-note/siyuan/issues/9519

```javascript
Uncaught TypeError: Failed to execute 'getAttribLocation' on 'WebGLRenderingContext': parameter 1 is not of type 'WebGLProgram'.
    at W.generateShaders (live2d_bundle.js:9:242567)
    at W.setupShaderProgram (live2d_bundle.js:9:237454)
    at $.drawMesh (live2d_bundle.js:9:259080)
    at W.setupClippingContext (live2d_bundle.js:9:234202)
    at $.doDrawModel (live2d_bundle.js:9:257769)
    at u.drawModel (live2d_bundle.js:9:226450)
    at d.doDraw (live2d_bundle.js:28:17348)
    at d.draw (live2d_bundle.js:28:17519)
    at I.onUpdate (live2d_bundle.js:28:3571)
    at g.render (live2d_bundle.js:28:22517)
    at N (live2d_bundle.js:26:4571)
```

定位代码：live2d_bundle.js:9 

```
 this._shaderSets.at(0).attributePositionLocation = this.gl.getAttribLocation(this._shaderSets.at(0).shaderProgram, "a_position"),
```

**Comment by HowcanoeWang** [comment]
已经在最新版思源中通过升级electron修复：https://github.com/siyuan-note/siyuan/issues/9705
